services:
  frontend:
    build: .
    container_name: taskmanager_frontend
    ports:
      - "5173:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
